version: '3'
services: 
  oxidized:
    image: myimage/oxidized:datetime
    restart: unless-stopped
    environment:
      CONFIG_RELOAD_INTERVAL: 864
    ports:
      - "8888:8888"
    volumes: 
      - ./oxidized_conf_dir/:/root/.config/oxidized/